version: 2.1

parameters:
  manifest-branch:
    type: string
    default: "master"
  device-tree:
    type: string
    default: "https://github.com/ashahir05/twrp_sm-127f"
  device-tree-branch:
    type: string
    default: "main"
  vendor-name:
    type: string
    default: "samsung"
  device-name:
    type: string
    default: "a12s"
  target:
    type: string
    default: "recoveryimage"
  build-type:
    type: string
    default: "eng"

jobs:
  setup:
    machine:
      image: ubuntu-2204:current
    resource_class: large

    steps:
      - run:
          name: Install build dependencies
          command: |
            sudo apt install -y \
              gperf \
              gcc-multilib \
              gcc-10-multilib \
              g++-multilib \
              g++-10-multilib \
              ccache \
              libc6-dev \
              lib32ncurses5-dev \
              x11proto-core-dev \
              libx11-dev \
              tree \
              lib32z-dev \
              libgl1-mesa-dev \
              libxml2-utils \
              xsltproc \
              bc \
              openjdk-8-jdk \
              lib32readline-dev \
              lib32z1-dev \
              liblz4-tool \
              libncurses5-dev \
              libncurses5 \
              libtinfo5 \
              libsdl1.2-dev \
              libwxgtk3.0-gtk3-dev \
              libxml2 \
              lzop \
              pngcrush \
              schedtool \
              squashfs-tools \
              imagemagick \
              libbz2-dev \
              lzma \
              ncftp \
              qemu-user-static \
              libstdc++-10-dev \
              python2

      - run:
          name: Setup swap
          command: |
            sudo dd if=/dev/zero of=/swapfile bs=12MB count=1024
            sudo chmod 600 /swapfile
            sudo mkswap /swapfile
            sudo swapon /swapfile

            sudo modprobe zram
            sudo zramctl /dev/zram0 --algorithm zstd --size 56G
            sudo mkswap /dev/zram0
            sudo swapon --priority 150 /dev/zram0

            sudo sysctl vm.swappiness=180
            sudo sysctl vm.watermark_boost_factor=0
            sudo sysctl vm.watermark_scale_factor=125
            sudo sysctl vm.page-cluster=0

      - run:
          name: Fetch sources
          command: |
            git config --global user.name "Ahmed Shahir"
            git config --global user.email "ashahir-build-circleci@xyz.pqr"

            git clone https://gitlab.com/OrangeFox/misc/scripts

            mkdir -p ${CIRCLE_WORKING_DIRECTORY}/OrangeFox
            cd ${CIRCLE_WORKING_DIRECTORY}/OrangeFox
            git clone https://github.com/ashahir05/orangefox-sync

      - run:
          name: Prepare for building
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/scripts
            sudo bash setup/android_build_env.sh

            cd ${CIRCLE_WORKING_DIRECTORY}/OrangeFox/sync
            ./orangefox_sync.sh --branch << pipeline.parameters.manifest-branch >> --path ${CIRCLE_WORKING_DIRECTORY}/OrangeFox/fox_<< pipeline.parameters.manifest-branch >>

      - run:
          name: Get device tree
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/OrangeFox/fox_<< pipeline.parameters.manifest-branch >>
            rm -rf ./device/<< pipeline.parameters.vendor-name >>/<< pipeline.parameters.device-name >>
            git clone << pipeline.parameters.device-tree >> -b << pipeline.parameters.device-tree-branch >> ./device/<< pipeline.parameters.vendor-name >>/<< pipeline.parameters.device-name >>

  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large

    steps:
      - run:
          name: Build
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/OrangeFox/fox_<< pipeline.parameters.manifest-branch >>
            set +e
            source build/envsetup.sh

            export ALLOW_MISSING_DEPENDENCIES=true

            # export OF_PATCH_VBMETA_FLAG=1
            export OF_AB_DEVICE=1
            export FOX_REMOVE_AAPT=1
            export FOX_DRASTIC_SIZE_REDUCTION=1
            export OF_VANILLA_BUILD=1
            export OF_USE_TWRP_SAR_DETECT=1
            export OF_PATCH_AVB20=1
            export FOX_USE_BASH_SHELL=1
            export FOX_ASH_IS_BASH=1
            export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
            export OF_CHECK_OVERWRITE_ATTEMPTS=1
            export OF_CLOCK_POS=1
            export OF_ALLOW_DISABLE_NAVBAR=1

            set -e

            rm -rf ${CIRCLE_WORKING_DIRECTORY}/OrangeFox/fox_<< pipeline.parameters.manifest-branch >>/out
            lunch twrp_<< pipeline.parameters.device-name >>-<< pipeline.parameters.build-type >> && make clean && mka adbd << pipeline.parameters.target >>

      - persist_to_workspace:
          root: ${CIRCLE_WORKING_DIRECTORY}/OrangeFox/fox_<< pipeline.parameters.manifest-branch >>/out/target/product/
          paths:
            - << pipeline.parameters.device-name >>

  publish:
    machine:
      image: ubuntu-2204:current
    resource_class: medium

    steps:
      - attach_workspace:
          at: releases
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${GITHUB_USERNAME} -r ${GITHUB_REPO} -c ${CIRCLE_SHA1} -delete ${CIRCLE_SHA1} releases/<< pipeline.parameters.device-name >>/*.img
            ghr -t ${GITHUB_TOKEN} -u ${GITHUB_USERNAME} -r ${GITHUB_REPO} -c ${CIRCLE_SHA1} -delete ${CIRCLE_SHA1} releases/<< pipeline.parameters.device-name >>/*.tar
            ghr -t ${GITHUB_TOKEN} -u ${GITHUB_USERNAME} -r ${GITHUB_REPO} -c ${CIRCLE_SHA1} -delete ${CIRCLE_SHA1} releases/<< pipeline.parameters.device-name >>/*.zip

workflows:
  build-recovery:
    jobs:
      - hold:
          type: approval
      - setup:
          requires:
            - hold
      - build:
          requires:
            - setup
      - publish:
          requires:
            - build
